plugins {
	id "base"
}

allprojects {
	group = "com.luneruniverse.minecraft.nbtdatabase"
	version = "0.0.2-SNAPSHOT"
}

subprojects {
	apply plugin: "java-library"
	apply plugin: "maven-publish"
	
	java.sourceCompatibility = JavaVersion.VERSION_1_8
	java.targetCompatibility = JavaVersion.VERSION_1_8
	
	repositories {
		mavenCentral()
		maven {
			url = uri("https://jitpack.io")
		}
	}
	
	jar {
		archiveBaseName.set("${rootProject.name}-${project.name}")
	}
	
	plugins.withId("com.gradleup.shadow") {
		build.dependsOn "shadowJar"
		tasks.named("shadowJar") {
			archiveBaseName.set("${rootProject.name}-${project.name}")
		}
	}
	
	publishing {
		publications {
			maven(MavenPublication) {
				from(components.java)
			}
		}
	}
}
