[libraries]
sqlite = "org.xerial:sqlite-jdbc:3.46.0.1"
google-gson = "com.google.code.gson:gson:2.13.1"
esotericsoftware-kryo = "com.esotericsoftware.kryo:kryo5:5.6.2"
querz-nbt = "com.github.Querz:NBT:6.1"

raphimc-minecraftauth = "net.raphimc:MinecraftAuth:5.0.1"

configurate-core = "org.spongepowered:configurate-core:4.2.0"
configurate-yaml = "org.spongepowered:configurate-yaml:4.2.0"
mega12345mega-nettymux = "com.github.mega12345mega:Netty-Multiplexer:2.0.0"
owasp-encoder = "org.owasp.encoder:encoder:1.3.1"
lenni0451-httpclient = "net.lenni0451.commons:httpclient:1.9.2"
mega12345mega-simplecli = "com.github.mega12345mega:Simple-CLI:0.0.2"

slf4j-simple = "org.slf4j:slf4j-simple:2.0.13"

filekit-dialogs = "io.github.vinceglb:filekit-dialogs:0.14.2"

[plugins]
shadow = "com.gradleup.shadow:9.0.0-rc1"
